### ISSUE TITLE
server crashes when i enable plugin

### ISSUE THREAD

**Issue by Hormxn** [HydrolienF/Underilla#13]
also, is there any discord i could use so i can maintain a more direct connection, I'm running quite a decently sized server so this would be quite crucial for us

**Comment by HydrolienF** [comment]
Hi @Hr0m4nul 
I will need more infos about the crash to help you.
Can you send infos as Minecraft server version, Underilla version, paper, spigot, purpur ?
Crash logs etc.
You can ask for help on this Discord https://discord.gg/RPNbtRSFqG

**Comment by HydrolienF** [comment]
I would guess that you are Hormon.exe on Discord.
The issue was caused by an old map format.
The solution is to generate the map in the latest version of minecraft without Underilla 1st, then use that updated map for Underilla generation.
Supporting old map format with underilla is not planned as the current solution does not require much work and supporting all old map format would take ages.
Old map format not being supported is writen in the README.
